config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/about' => 'static_pages#about', as: :about
  get 'static_pages/contact' => 'static_pages#contact', as: :contact
  
  get '/portfolio' => 'portfolio#index', as: :portfolio
  get '/portfolio/runshow' => 'portfolio#runshow', as: :runshow
  get '/portfolio/sapphirerain' => 'portfolio#sapphirerain', as: :sapphirerain
  get '/portfolio/pokemonmemory' => 'portfolio#pokemonmemory', as: :pokemonmemory
  get '/portfolio/studybuddy' => 'portfolio#studybuddy', as: :studybuddy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
  end

  def runshow
    
  end

  def sapphirerain
    
  end

  def pokemonmemory
    
  end

  def studybuddy
    
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title MaRisa Jackson
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    %header
      %h1 MaRisa Jackson
      %h3.subheader Developer
      %nav
        %ul
          %li=link_to "About", about_path
          %li=link_to "Portfolio", portfolio_path
          %li=link_to "Contact", contact_path


    = yield
    = javascript_include_tag "application"

app/views/portfolio/index.html.haml
%ul.project-index
  %li
    =link_to runshow_path do
      .project
        %img(src='/assets/RunShow.png' alt='RunShow')

  %li
    =link_to sapphirerain_path do
      .project
        %img(src='/assets/Sapphire_Rain.png' alt='Sapphire Rain')

  %li
    =link_to pokemonmemory_path do
      .project
        %img(src='/assets/pokemon-memory.png' alt='Pokemon Memory')

  %li
    =link_to studybuddy_path do
      .project
        %img(src='/assets/study-buddy.png' alt='Study Buddy')

app/views/portfolio/pokemonmemory.html.haml
.project-img
  %img(src='/assets/pokemon-memory.png' alt='Pokemon Memory')
.project-summary
  %h1 Pokemon Memory
  %p A memory match game using Javascript and CSS animations

  %p= link_to "Live App", 'pokemon.marisajackson.com'
  %p= link_to "Github Repo", 'https://github.com/marisajackson/pokemon-memory'

app/views/portfolio/runshow.html.haml
.project-img
  %img(src='/assets/RunShow.png' alt='RunShow')
.project-summary
  %h1 RunShow
  %h4 Summary
  %p A concert management app for promoters and employees.

  %h4 Features
  %ul
    %li Promoters can sign in with Facebook
    %li Promoters can add venues and concerts
    %li Promoters can invite employees through email to the app
    %li Promoters can assign employees to particular concerts 
    %li Promoters can add and update expenses and incomes
    %li Employees can view and update their assigned concerts

  %h4 Technologies Used
  %ul
    %li Ruby on Rails
    %li TDD with Rspec/Capybara/Poltergeist
    %li HAML
    %li Postgres
    %li Postmark
    %li AJAX

  %p= link_to "Live App", 'runshow.herokuapp.com'
  
  %p= link_to "Github Repo", 'https://github.com/marisajackson/concert-management'

app/views/portfolio/sapphirerain.html.haml
.project-img
  %img(src='/assets/Sapphire_Rain.png' alt='Sapphire Rain')
.project-summary
  %h1 Sapphire Rain
  %p A top down dungeon crawler

  %p Capstone Project for Web Development section at Nashville Software School.

  %p I chose to implement a new technology, the Phaser HTML5 game framework, for my capstone project. The two-level top-down puzzle based game features a User Log In that will save your game progress using Node.js and MongoDB.

  %p= link_to "Live App", 'sapphire-rain.marisajackson.com'
  %p= link_to "Github Repo", 'https://github.com/marisajackson/sapphire-rain'

app/views/portfolio/studybuddy.html.haml
.project-img
  %img(src='/assets/study-buddy.png' alt='Study Buddy')
.project-summary
  %h1 Study Buddy
  %p An LMS Application

  %p Study Buddy was a group project made with Node.js. I was assigned with a team of 2 other students to build an LMS application. We spent the a large portion of our time planning the project appropriately and assigning specific tasks to each team member. Because of our planning, we were able to quickly implement all of the features on our project. 

  %p I worked on the course aspect of the project implementing the following features:
  %li Displaying the course study materials (a linked youtube video)
  %li Displaying and Submitting the course test using animations

  %p After the projects completion, I also spent some extra time refactoring the code and implementing flashcards into the study materials.

  %p= link_to "Live App", 'study-buddy.marisajackson.com'
  %p= link_to "Github Repo", 'https://github.com/marisajackson/study-buddy'

app/views/static_pages/about.html.haml
%img#about-image(src='/assets/marisajackson.jpg' alt='MaRisa Jackson')

#about-info
  %p After working various types of events, from the Super Bowl to SXSW to ComicCons across the country, I found that what I really enjoyed was working with technology. At most events, I quickly became the person who would be asked to troubleshoot the electronics and applications.
  
  %p Eventually I discovered CodeAcademy, which quickly pushed me down the path to becoming a developer. 

  %p In March 2014, I was accepted into the Nashville Software School. The school has given me experience with various technologies including Node.js and Ruby on Rails. I would love to take my newly learned skills and begin applying them to real world projects.

app/views/static_pages/contact.html.haml
%ul
  %li= link_to 'LinkedIn', 'http://www.linkedin.com/pub/marisa-jackson/4a/a08/b54/'
  %li= link_to 'Github', 'http://www.github.com/marisajackson'
  %li Email: mhljackson@gmail.com